### PR TITLE
Create alt text guide

### PR DESCRIPTION
**Pull request by isabela-pf**
From the two test sprints we've had, many people have had questions about styling when writing and reviewing others' alt text. 

This is a draft to address those questions (and maybe write a more comprehensive alt text guide than I've personally encountered).

### CODE REVIEW

**Comment by isabela-pf** [comment]
- [ ] Add diagram and plot guide.

**Comment by MarsBarLee** [comment]
I think most of the time, 'illustration' is as unnecessary as 'image'.

In a different context, say an art website, the distinction between an illustration and a photograph is important. 
"An photograph of the Seine river in 1904"
"An illustration  of the Seine river in 1904 by artist Claude Monet"

I personally haven't seen much screenshots in my experience with the NumPy website or documentation, so I can't say much on the usage of "screenshot". 

For "animation", I think  it's usage is similar to "video" or "panels" (as in comic panels). If understanding a sequence of events is crucial to understanding the image, then I think those words should be used.

**Comment by isabela-pf** [comment]
I've been thinking about this, and I think you're right. I think there's better ways to specify some of the things I was considering using more specific image words. Like for projects with UI (such as JupyterLab) I do think it's important to have a way to distinguish when an image is of that UI versus not because it explains where the information is meant to be used, but saying whether or not it's a screen shot isn't the only way.

I'll revisit with some other ideas! Thank you so much @MarsBarLee!

**Comment by isabela-pf** [comment]
This draft will work for the sake of our events, so I'm going to merge it. This is always open for more feedback!

**Pull request merged**
